sudo: required
dist: hirsute

services:
    - docker

script:
    - |
        docker run --rm -i \
          --name df-shellcheck \
          -v $PWD:/usr/src:ro \
          --workdir /usr/src \
          r.j3ss.co/shellcheck ./.test.sh

