- name: Set up local workstation
  hosts: local
  vars_files:
    - ./vars/custom.yml
  roles:
    - role: base
      tags:
        - base
    - role: git
      tags:
        - git
    - role: zsh
      tags:
        - zsh
    - role: tmux
      tags:
        - tmux
    - role: vim
      tags:
        - vim
    - role: code
      tags:
        - code
    - role: swerty
      tags:
        - swerty
