- name: Set up local workstation
  hosts: local
  vars_files:
    - ./vars/custom.yml
  roles:
    - role: base
      tags:
        - base
        - minimum
    - role: git
      tags:
        - git
        - minimum
    - role: zsh
      tags:
        - zsh
        - minimum
    - role: tmux
      tags:
        - tmux
        - minimum
    - role: vim
      tags:
        - vim
        - minimum
    - role: code
      tags:
        - code
    - role: swerty
      tags:
        - swerty
        - x11
    - role: gnome
      tags:
        - gnome
