---
###############################################################################
# Visual Code

- name: Visual Code | Install package | package 
  become: yes
  become_user: root
  package:
    name:
      - "code"
    update_cache: yes

- name: Visual Code | Install extensions | command
  loop: "{{ visual_code_extensions }}"
  tags: code_extensions
  command: code --install-extension "{{ item }}"
