base_packages:
  - htop
  - vim
  - tmux
  - zsh
  - mosh
  - curl
  - wget
  - git
  - tig
  - ranger
  - fzf
  - xsel
  - xclip

macos_packages:
  - fd
  - rga

deb_packages:
  - python3-venv
  - python3-pip
  - fd-find
  - ripgrep
