---
###############################################################################
# Zsh installation

- name: zsh | Installs zsh | package
  become: yes
  become_user: root
  package:
    name: zsh
    state: present

- name: zsh | Sets zsh as default shell for root | command
  become: yes
  become_user: root
  command: chsh -s /bin/zsh
  register: zsh_for_root
  failed_when: zsh_for_root.rc >= 1
  changed_when: "'not changed' not in zsh_for_root.stderr" 

# - debug:
# msg: :{{zsh_for_root}}

- name: zsh | Sets zsh as default shell for {{ dotfiles_user }} | command
  become: yes
  become_user: root
  command: chsh -s /bin/zsh {{ dotfiles_user }}
  register: zsh_for_user
  failed_when: zsh_for_user.rc >= 1
  changed_when: "'not changed' not in zsh_for_user.stderr"

- name: zsh | Checks for oh-my-zsh installation | stat
  stat:
    path: "{{ dotfiles_user_home }}/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: zsh | Installs oh-my-zsh | raw
  raw: 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  when: not oh_my_zsh_stat.stat.exists

- name: zsh | Copies .zshrc | template
  template:
    src: "zshrc.j2"
    dest: "{{ dotfiles_user_home }}/.zshrc"
