---
###############################################################################
# Zsh configuration

- name: zsh | Sets zsh as default shell for root | user
  become: yes
  user:
    name: "{{ dotfiles_user }}"
    shell: /bin/zsh

- name: zsh | Sets zsh as default shell for {{ dotfiles_user }} | user
  become: yes
  user:
    name: "{{ dotfiles_user }}"
    shell: /bin/zsh

- name: zsh | Checks for oh-my-zsh installation | stat
  stat:
    path: "{{ dotfiles_user_home }}/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: zsh | Installs oh-my-zsh | raw
  raw: 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  when: not oh_my_zsh_stat.stat.exists

- name: zsh | Copies .zshrc | template
  template:
    src: "zshrc.j2"
    dest: "{{ dotfiles_user_home }}/.zshrc"
