---
###############################################################################
# Tmux configuration

- name: Tmux | Install Powerline | pip
  pip:
    name: powerline-status

# - name: Print all available facts
  # ansible.builtin.debug:
    # var: ansible_facts

- name: Tmux | Copies .tmux.conf | template
  template:
    src: "tmux.conf.j2"
    dest: "{{ dotfiles_user_home }}/.tmux.conf"

- name: zsh | Installs TPM from Github | git
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ dotfiles_user_home }}/.tmux/plugins/tpm"
