---
###############################################################################
# Tmux configuration

- name: Tmux | Links .tmux.conf file | file
  file:
    src: "{{ dotfiles_home }}/roles/tmux/files/tmux.conf.link"
    dest: "{{ dotfiles_user_home }}/.tmux.conf"
    state: link
    force: yes

- name: zsh | Installs TPM from Github | git
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "{{ dotfiles_user_home }}/.tmux/plugins/tpm"
