material_shell_binds:
- { key: "app-launcher", value: "['<Control><Alt><Super>x']" }
- { key: "kill-focused-window", value: "['<Control><Alt><Super>q']" }
- { key: "last-workspace", value: "['<Control><Alt><Super>z']" }
- { key: "cycle-tiling-layout", value: "['<Control><Alt><Super>space']" }
- { key: "move-window-monitor-down", value: "['<Control><Alt><Super><Shift>u']" }
- { key: "move-window-monitor-left", value: "['<Control><Alt><Super><Shift>y']" }
- { key: "move-window-monitor-right", value: "['<Control><Alt><Super><Shift>o']" }
- { key: "move-window-monitor-up", value: "['<Control><Alt><Super><Shift>i']" }
- { key: "move-window-left", value: "['<Control><Alt><Super>y']" }
- { key: "move-window-right", value: "['<Control><Alt><Super>o']" }
- { key: "move-window-top", value: "['<Control><Alt><Super>i']" }
- { key: "move-window-bottom", value: "['<Control><Alt><Super>u']" }
- { key: "move-window-to-workspace-1", value: "['<Control><Alt><Super><Shift>1']" }
- { key: "move-window-to-workspace-10", value: "['<Control><Alt><Super><Shift>0']" }
- { key: "move-window-to-workspace-2", value: "['<Control><Alt><Super><Shift>2']" }
- { key: "move-window-to-workspace-3", value: "['<Control><Alt><Super><Shift>3']" }
- { key: "move-window-to-workspace-4", value: "['<Control><Alt><Super><Shift>4']" }
- { key: "move-window-to-workspace-5", value: "['<Control><Alt><Super><Shift>5']" }
- { key: "move-window-to-workspace-6", value: "['<Control><Alt><Super><Shift>6']" }
- { key: "move-window-to-workspace-7", value: "['<Control><Alt><Super><Shift>7']" }
- { key: "move-window-to-workspace-8", value: "['<Control><Alt><Super><Shift>8']" }
- { key: "move-window-to-workspace-9", value: "['<Control><Alt><Super><Shift>9']" }
- { key: "navigate-to-workspace-1", value: "['<Control><Alt><Super>1']" }
- { key: "navigate-to-workspace-10", value: "['<Control><Alt><Super>0']" }
- { key: "navigate-to-workspace-2", value: "['<Control><Alt><Super>2']" }
- { key: "navigate-to-workspace-3", value: "['<Control><Alt><Super>3']" }
- { key: "navigate-to-workspace-4", value: "['<Control><Alt><Super>4']" }
- { key: "navigate-to-workspace-5", value: "['<Control><Alt><Super>5']" }
- { key: "navigate-to-workspace-6", value: "['<Control><Alt><Super>6']" }
- { key: "navigate-to-workspace-7", value: "['<Control><Alt><Super>7']" }
- { key: "navigate-to-workspace-8", value: "['<Control><Alt><Super>8']" }
- { key: "navigate-to-workspace-9", value: "['<Control><Alt><Super>9']" }
- { key: "next-window", value: "['<Control><Alt><Super>l']" }
- { key: "next-workspace", value: "['<Control><Alt><Super>j']" }
- { key: "previous-window", value: "['<Control><Alt><Super>h']" }
- { key: "previous-workspace", value: "['<Control><Alt><Super>k']" }
- { key: "resize-window-down", value: "['<Control><Alt><Super><Shift>j']" }
- { key: "resize-window-left", value: "['<Control><Alt><Super><Shift>h']" }
- { key: "resize-window-right", value: "['<Control><Alt><Super><Shift>l']" }
- { key: "resize-window-up", value: "['<Control><Alt><Super><Shift>k']" }
- { key: "toggle-material-shell-ui", value: "['<Control><Alt><Super>escape']" }
