---
###############################################################################
# Base system

- name: Base | Installs packages | package
  become: yes
  become_user: root
  loop: "{{ base_packages }}"
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
