---
###############################################################################
# Vim installation

- name: Vim | Installs Vim | package
  become: yes
  become_user: root
  package:
    name: vim
    state: present
    update_cache: yes

- name: Vim | SpaceVim | command
  command: curl -sLf https://spacevim.org/install.sh | bash
  args:
    creates: "{{ dotfiles_user_home }}/.SpaceVim"

- name: Vim | SpaceVim | command
  file:
    path: "{{ dotfiles_user_home }}/.SpaceVim.d"
    state: directory

- name: Vim | Copy custom SpaceVim config file | file
  file:
    src: "{{ dotfiles_home }}/roles/vim/files/init.toml.link"
    dest: "{{ dotfiles_user_home }}/.SpaceVim.d/init.toml"
    state: link
    force: yes


