---
###############################################################################
# Vim configuration

- name: Vim | Checks for SpaceVim installation | stat
  stat:
    path: "{{ dotfiles_user_home }}/.SpaceVim/"
  register: spacevim_stat

- name: Vim | Installs SpaceVim | raw
  raw: 'sh -c "$(curl -fsSL https://spacevim.org/install.sh)" -f -y'
  when: not spacevim_stat.stat.exists

- name: Vim | SpaceVim | command
  file:
    path: "{{ dotfiles_user_home }}/.SpaceVim.d"
    state: directory

- name: Vim | Copy custom SpaceVim config file | file
  file:
    src: "{{ dotfiles_home }}/roles/vim/files/init.toml.link"
    dest: "{{ dotfiles_user_home }}/.SpaceVim.d/init.toml"
    state: link
    force: yes


